# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

FROM xrt

# Where we'll install the build backend
WORKDIR /IRON
COPY docker/setup.sh /IRON/
COPY docker/entrypoint.sh /entrypoint.sh

# Set environment variable to suppress prompts in scripts
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-l", "-c"]

# Install XDNA driver
RUN dpkg -i /XDNA/debs/xrt_*x86_64-amdxdna.deb

RUN git clone --recursive https://github.com/xilinx/mlir-aie.git /IRON/mlir-aie && \
    cd /IRON/mlir-aie && \
    git checkout c105c0b && \
    git submodule update --recursive

# Comment out NPU check - we don't have access to /dev/accel during docker build
RUN sed -i '31s/^/#/' /IRON/mlir-aie/utils/quick_setup.sh

# Lock down wheels
RUN sed -i '61s|.*|pip install mlir_aie -f https://github.com/Xilinx/mlir-aie/releases/download/latest-wheels/mlir_aie-0.0.1.2025051904+c105c0b-cp312-cp312-manylinux_2_35_x86_64.whl|' /IRON/mlir-aie/utils/quick_setup.sh

RUN sed -i '64s|.*|pip install llvm_aie -f https://github.com/Xilinx/llvm-aie/releases/download/nightly/llvm_aie-19.0.0.2025041501+b2a279c1-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl|' /IRON/mlir-aie/utils/quick_setup.sh

# IRON requires python venv
RUN apt -y install python3.12-venv

# Make life easier
RUN apt -y install vim

# Setup IRON
RUN cd /IRON/mlir-aie && \
    source /opt/xilinx/xrt/setup.sh && \
    source /IRON/mlir-aie/utils/quick_setup.sh

# Copy the new AIE pragma utils.h to mlir_aie/include/ so it's picked up when doing #include "aie_kernel_utils.h"
RUN cp /IRON/mlir-aie/aie_kernels/aie_kernel_utils.h /IRON/mlir-aie/ironenv/lib/python3.12/site-packages/mlir_aie/include/

# Install NPUEval
COPY . /IRON/npueval/
RUN source /IRON/setup.sh && \
    cd /IRON/npueval && \
    python3 -m pip install .

# Install jupyter for notebooks
RUN source /IRON/setup.sh && \
    python3 -m pip install jupyterlab

# (optional) This will only run if it detects docker/ryzen_ai-1.3.0ea1.tgz and docker/Xilinx.lic
RUN /IRON/npueval/docker/install_aie_essentials.sh

# Cleanup
ENV SHELL=/bin/bash

# Make sure to source the setup script on docker start
ENTRYPOINT ["/entrypoint.sh"]
